services:
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-api
    command: sh -c "npm install --workspaces && npm run --workspace=@image-processing/backend start"
    environment:
      NODE_ENV: development
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FIREBASE_SERVICE_ACCOUNT_KEY_BASE64: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiaW1hZ2UtcHJvY2Vzc2luZy1mZjE0ZSIsCiAgInByaXZhdGVfa2V5X2lkIjogIjA5MTA0MzQxMjEwMWFlMzQ3MWM0NTE0MjRlZTAwYTg2MTc3ZTRiYzciLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3JaN0tKQWkxbHdyOUhcbm1ka3c0cGIzcTA4c1NNRW9UYWs0WlViUDRycDY5eDc3YTlScE1vMW9oQWMzYksvRFZlNFU0VFZ1NWNIbk5HRktcbktvbW9pVy92STJ2RGMyaWVoQWVUK1FDVmFnWit5NFQ4aFN0bmp4Vi9QZm9EcXhwZGdHbDdNZUQxeURseFhMMFZcbjR5N2dNeGVOcitQaEJpeXk2cG9EYTBKamtqRndyeGVTMnd6STBQakFkL2dCZXBmUFB1Yk5BUG84SVZ5MFpiOElcbjhOdmRRR0tyMGMwRU5xaHJhb0paV3F0bVpTbGFDUzZxeHJiNzd6ZEEyUVpMU0FYU2l4UktIbWh4b2RrQzFmdXFcbkFLTkJlUUd1dnlWbWtmSTJrNEp1TGNCOGxwSDlTcExpZGdJc3M4TGhXQTR6RkE4blFYYkdaS2l4VEVQOUc4THJcbjVqS1NZeG1WQWdNQkFBRUNnZ0VBT3dRd1Y3WTFOVlZ4a05DckZJYmdIaFNRNVJtRDBFRzFJeUxUMTk0a0FSUzNcblNUQWVhYjRyTERKUlhjY0JXWXRydHlxM3dDQkJ2RDZ2eE42U21VSUJGV0NueVJzaWlYbkNOalBFL0swTjRYaG5cbnFKNmRqRUdhMEQzaHFJT3dSME5nampkbFVwc0hGRDR2S0tzWlI3NnZ2R3cwVlJWUUxLWlVNeHNxTjZodGQzTndcbjFiMGhRTWh1azloRjBrRXltWWZLNktFdHIrMFhBMzRnSjJVOXkrZERUTXBJQThOcXlNRWM4aFY4eHJCMGJoM3RcbjRMWUc2bEFHRFA5RGgzSklIZWxsUFFWQjF1QmVlYlh6RXhFVmpuUHYwTyszeGsydW8xbWVEeGdwRU14Ymo3eGZcbko5WmJJaks4TWs0ZzNnVHRKTFR5QkpKdkhNKzVBVzA3bjlMMm9pbUJmUUtCZ1FEcDFFdnd4T0dqd0k3VUtJYnZcbllaeVF6ZHdGdnFsR0Ixb1lWek54bEhsc1JBNTU5Q24xOVlxVHNOK2FWY2xtYkdwZFM0bFN3dlNwdzAvZ3ZpeEFcbmYvaTJsWnVkK25PL0QxbGtpRVphV3lTLzBoRCthSFBkeElGY0tzUUZ3ZDVVV0J1aTJadWhjWlRRY1dpM0QxS1FcbllLRE5yUWVvbFBVZTJjZC9namRDRTZXWUV3S0JnUUM3cUMva0V2dGdWMjJCaDAwMHA5UmN4ck8wbzZYR2pRb29cbldiV2tSRmN6V1o3YVBPY2dxZk1RTnVPL284allXampXY29RYjhKQnpPZmtBb0dMQzdUTEZkamloVTdsK1VjZ1Ncbk04REtLNEZma0krRFF1V21oZ00wRmJaODVrcUNBbGxxSUl3RXE5b2N4cjVDaS93WEh1blQzU1oxRFYzcmpKQU5cbkNSdW5SZU9NdHdLQmdIdTFyd3ZPRGhibHZHc3dtZHN5U0hRd0JiVWdYMHhHZlhzZFA0RmE3VGJEZHVrOHJhcU1cbll1bXFqVktKQ29uZTJCTk44SFJSNHNHaUxMT1p5YTNDUnVMS21rOWxmekZaUEpFOHJBUUg3cFJ4M2ozTEkybjBcbkdnQ2FPNlZVSVgxOE0vcmZxRUFzNkcrellKUmhUZXhHd3l5dDI3eHNPcGM4M3hodDJ6QmhWcDN6QW9HQU9kcS9cbmNSUjlGWlcrdUJscnJ4a3krcXQwQ2ZRT0R1bTZ3UGZ2YlVaNGorZElkMFloaDh0OW1Ya2l2Qm1WdVVZUGtlWGFcblh2Ykt3Z3VVZmlIMGNONUtNZUNoMHZNS0ZDeklmdndmcXZUQXZTTEhiQk42MDkwckxhcW9DVmZDanRTRWxwaVVcbk1uaDlGVFFjd2syQUdleTQ4RTJWSnE5SlRtNldscjVCSFZBSnVIOENnWUJ4L1ZQWGdockdPUUgzRDQ3ZWFPMHlcbllETVc3ekxhMEVQWmovSDlGV1hwUGtTNWYxbktTRkNNVnp2NFZJakJ5elJHVU9NQ1BZUXMzQnlLNy84R2V3OUhcbk1zbklXM29kaEtvVTV1TzNad2pQTERMTFIrUkJvdFNOODZJZHFYWGhBUWN3RmhVQXBIZ1BIUythWm1Qdm1PSmJcbmlhbWZyN1gvWUwrMThQZGtBSTRFZnc9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQGltYWdlLXByb2Nlc3NpbmctZmYxNGUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTEzMDQ0MzA0NDI5MTA4NzU0NTk0IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay1mYnN2YyU0MGltYWdlLXByb2Nlc3NpbmctZmYxNGUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-worker
    command: sh -c "npm install --workspaces && npm run --workspace=@image-processing/backend start:worker"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FIREBASE_SERVICE_ACCOUNT_KEY_BASE64: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiaW1hZ2UtcHJvY2Vzc2luZy1mZjE0ZSIsCiAgInByaXZhdGVfa2V5X2lkIjogIjA5MTA0MzQxMjEwMWFlMzQ3MWM0NTE0MjRlZTAwYTg2MTc3ZTRiYzciLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3JaN0tKQWkxbHdyOUhcbm1ka3c0cGIzcTA4c1NNRW9UYWs0WlViUDRycDY5eDc3YTlScE1vMW9oQWMzYksvRFZlNFU0VFZ1NWNIbk5HRktcbktvbW9pVy92STJ2RGMyaWVoQWVUK1FDVmFnWit5NFQ4aFN0bmp4Vi9QZm9EcXhwZGdHbDdNZUQxeURseFhMMFZcbjR5N2dNeGVOcitQaEJpeXk2cG9EYTBKamtqRndyeGVTMnd6STBQakFkL2dCZXBmUFB1Yk5BUG84SVZ5MFpiOElcbjhOdmRRR0tyMGMwRU5xaHJhb0paV3F0bVpTbGFDUzZxeHJiNzd6ZEEyUVpMU0FYU2l4UktIbWh4b2RrQzFmdXFcbkFLTkJlUUd1dnlWbWtmSTJrNEp1TGNCOGxwSDlTcExpZGdJc3M4TGhXQTR6RkE4blFYYkdaS2l4VEVQOUc4THJcbjVqS1NZeG1WQWdNQkFBRUNnZ0VBT3dRd1Y3WTFOVlZ4a05DckZJYmdIaFNRNVJtRDBFRzFJeUxUMTk0a0FSUzNcblNUQWVhYjRyTERKUlhjY0JXWXRydHlxM3dDQkJ2RDZ2eE42U21VSUJGV0NueVJzaWlYbkNOalBFL0swTjRYaG5cbnFKNmRqRUdhMEQzaHFJT3dSME5nampkbFVwc0hGRDR2S0tzWlI3NnZ2R3cwVlJWUUxLWlVNeHNxTjZodGQzTndcbjFiMGhRTWh1azloRjBrRXltWWZLNktFdHIrMFhBMzRnSjJVOXkrZERUTXBJQThOcXlNRWM4aFY4eHJCMGJoM3RcbjRMWUc2bEFHRFA5RGgzSklIZWxsUFFWQjF1QmVlYlh6RXhFVmpuUHYwTyszeGsydW8xbWVEeGdwRU14Ymo3eGZcbko5WmJJaks4TWs0ZzNnVHRKTFR5QkpKdkhNKzVBVzA3bjlMMm9pbUJmUUtCZ1FEcDFFdnd4T0dqd0k3VUtJYnZcbllaeVF6ZHdGdnFsR0Ixb1lWek54bEhsc1JBNTU5Q24xOVlxVHNOK2FWY2xtYkdwZFM0bFN3dlNwdzAvZ3ZpeEFcbmYvaTJsWnVkK25PL0QxbGtpRVphV3lTLzBoRCthSFBkeElGY0tzUUZ3ZDVVV0J1aTJadWhjWlRRY1dpM0QxS1FcbllLRE5yUWVvbFBVZTJjZC9namRDRTZXWUV3S0JnUUM3cUMva0V2dGdWMjJCaDAwMHA5UmN4ck8wbzZYR2pRb29cbldiV2tSRmN6V1o3YVBPY2dxZk1RTnVPL284allXampXY29RYjhKQnpPZmtBb0dMQzdUTEZkamloVTdsK1VjZ1Ncbk04REtLNEZma0krRFF1V21oZ00wRmJaODVrcUNBbGxxSUl3RXE5b2N4cjVDaS93WEh1blQzU1oxRFYzcmpKQU5cbkNSdW5SZU9NdHdLQmdIdTFyd3ZPRGhibHZHc3dtZHN5U0hRd0JiVWdYMHhHZlhzZFA0RmE3VGJEZHVrOHJhcU1cbll1bXFqVktKQ29uZTJCTk44SFJSNHNHaUxMT1p5YTNDUnVMS21rOWxmekZaUEpFOHJBUUg3cFJ4M2ozTEkybjBcbkdnQ2FPNlZVSVgxOE0vcmZxRUFzNkcrellKUmhUZXhHd3l5dDI3eHNPcGM4M3hodDJ6QmhWcDN6QW9HQU9kcS9cbmNSUjlGWlcrdUJscnJ4a3krcXQwQ2ZRT0R1bTZ3UGZ2YlVaNGorZElkMFloaDh0OW1Ya2l2Qm1WdVVZUGtlWGFcblh2Ykt3Z3VVZmlIMGNONUtNZUNoMHZNS0ZDeklmdndmcXZUQXZTTEhiQk42MDkwckxhcW9DVmZDanRTRWxwaVVcbk1uaDlGVFFjd2syQUdleTQ4RTJWSnE5SlRtNldscjVCSFZBSnVIOENnWUJ4L1ZQWGdockdPUUgzRDQ3ZWFPMHlcbllETVc3ekxhMEVQWmovSDlGV1hwUGtTNWYxbktTRkNNVnp2NFZJakJ5elJHVU9NQ1BZUXMzQnlLNy84R2V3OUhcbk1zbklXM29kaEtvVTV1TzNad2pQTERMTFIrUkJvdFNOODZJZHFYWGhBUWN3RmhVQXBIZ1BIUythWm1Qdm1PSmJcbmlhbWZyN1gvWUwrMThQZGtBSTRFZnc9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQGltYWdlLXByb2Nlc3NpbmctZmYxNGUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTEzMDQ0MzA0NDI5MTA4NzU0NTk0IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay1mYnN2YyU0MGltYWdlLXByb2Nlc3NpbmctZmYxNGUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:3000/api"
    container_name: frontend
    ports:
      - "5173:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped
    environment:
      NODE_ENV: development
