services:
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-api
    command: sh -c "npm install --workspaces && npm run --workspace=@image-processing/backend start"
    environment:
      NODE_ENV: development
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-worker
    command: sh -c "npm install --workspaces && npm run --workspace=@image-processing/backend start:worker"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
